#Définition du nom WorkFlow
name: Show "Hello Word"

# trigger manuel
on:
  workflow_dispatch:

# Travaux à réaliser
jobs:
 #Nom du job
  show_hello:
    runs-on: windows-latest
    steps:
      #Nom et l'action de l'etape
      - name: print_hello
        run: echo "Hello World !"